//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SapReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FORM&gt;
        ///&lt;nl&gt;
        ///-&lt;/nl&gt;
        ///&lt;label location=&quot;12,12&quot; font=&quot;24&quot;&gt;SapChat Beta&lt;/label&gt;
        ///&lt;richtextbox location=&quot;12,50&quot; size=&quot;911,322&quot; readonly=&quot;&quot; name=&quot;box&quot;/&gt;
        ///&lt;richtextbox location=&quot;12,380&quot; size=&quot;777,134&quot; name=&quot;ent&quot;/&gt;
        ///&lt;button location=&quot;789,380&quot; font=&quot;14&quot; size=&quot;134&quot; click=&quot;Send:&quot; name=&quot;send&quot;&gt;Отправить&lt;/button&gt;
        ///&lt;script&gt;
        ///Send:
        ///#box=@Parse(#box#nl#ent)
        ///#ent = null;
        ///&lt;/script&gt;
        ///&lt;/FORM&gt;.
        /// </summary>
        internal static string CHAT {
            get {
                return ResourceManager.GetString("CHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FORM&gt; 
        ///&lt;label location=&quot;12,12&quot; font=&quot;12&quot; &gt;Поменять имя&lt;/label&gt; 
        ///&lt;label location=&quot;222,42&quot; font=&quot;10&quot; &gt;Новое имя&lt;/label&gt; 
        ///
        ///&lt;textbox location=&quot;12,42&quot; size=&quot;200,20&quot; name=&quot;newName&quot;&gt;&lt;/textbox&gt; 
        ///
        ///&lt;label location=&quot;12,72&quot; font=&quot;12&quot; &gt;Поменять пароль&lt;/label&gt; 
        ///
        ///&lt;label location=&quot;222,102&quot; font=&quot;10&quot; &gt;Старый пароль&lt;/label&gt; 
        ///&lt;textbox location=&quot;12,102&quot; size=&quot;200,20&quot; name=&quot;oldPass&quot; secured=&quot;&quot;&gt;&lt;/textbox&gt; 
        ///&lt;label location=&quot;222,132&quot; font=&quot;10&quot; &gt;Новый пароль&lt;/label&gt; 
        ///&lt;textbox location=&quot;12,132&quot; size=&quot;200,20&quot; name=&quot;newPas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ls1 {
            get {
                object obj = ResourceManager.GetObject("ls1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FORM name=&quot;test&quot;&gt;
        ///&lt;button size=&quot;100&quot; name=&quot;ses&quot; click=&quot;Main&quot;/&gt;
        ///&lt;script&gt;
        ///function Main()
        ///Alert(_(&quot;ses&quot;).text)
        ///end
        ///&lt;/script&gt;
        ///&lt;/FORM&gt;.
        /// </summary>
        internal static string LSSL {
            get {
                return ResourceManager.GetString("LSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FORM name=&quot;Pro&quot; author=&quot;LISENKO SOFT&quot;&gt;
        ///&lt;label location=&quot;12,12&quot; font=&quot;18&quot; name=&quot;hi&quot;&gt;Добро пожаловать&lt;/label&gt;
        ///
        ///&lt;label location=&quot;12,50&quot; font=&quot;12&quot;&gt;Плагины&lt;/label&gt;
        ///&lt;button location=&quot;15,80&quot; name=&quot;addPlugin&quot;&gt;Добавить плагин&lt;/button&gt;
        ///&lt;button location=&quot;15,110&quot; name=&quot;libPlugin&quot;&gt;Библиотека плагинов&lt;/button&gt;
        ///&lt;button location=&quot;15,140&quot; name=&quot;proPlugin&quot;&gt;Pro плагины&lt;/button&gt;
        ///
        ///
        ///&lt;label location=&quot;12,200&quot; font=&quot;12&quot;&gt;Облако&lt;/label&gt;
        ///&lt;button location=&quot;15,230&quot; name=&quot;addCloud&quot;&gt;Добавить облако&lt;/button&gt;
        ///&lt;button location=&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PRO {
            get {
                return ResourceManager.GetString("PRO", resourceCulture);
            }
        }
    }
}
