//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SapReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FORM name=&quot;Добро пожаловать!&quot; noparse=&quot;&quot;&gt;
        ///	&lt;label location=&quot;12,12&quot; font=&quot;18&quot;&gt;Добро пожаловать!&lt;/label&gt;
        ///	&lt;hi&gt;Дарова ёпта!&lt;/hi&gt;
        ///	&lt;bye&gt;Пока ёпта!&lt;/bye&gt;
        ///	&lt;combobox readonly=&quot;&quot; change=&quot;${show} = ?(#{list},lel,#{hi},#{bye});#{field} = ${show};&quot; location=&quot;12,50&quot; size=&quot;134,20&quot; name=&quot;list&quot;&gt;
        ///		&lt;option&gt;lel&lt;/option&gt;
        ///		&lt;option&gt;ses&lt;/option&gt;
        ///	&lt;/combobox&gt;
        ///	&lt;richtextbox readonly=&quot;&quot; location=&quot;12,80&quot; size=&quot;420,134&quot; name=&quot;field&quot;&gt;&lt;/richtextbox&gt;
        ///&lt;/FORM&gt;.
        /// </summary>
        internal static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ls1 {
            get {
                object obj = ResourceManager.GetObject("ls1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FORM name=&quot;LIENKO SOFT security lite&quot; author=&quot;LIENKO SOFT&quot;&gt;
        ///	&lt;label location=&quot;12,12&quot; font=&quot;18&quot;&gt;LSsec lite&lt;/label&gt;
        ///	&lt;textbox location=&quot;12,50&quot; size=&quot;420,20&quot; name=&quot;key&quot;&gt;Введите ключ&lt;/textbox&gt;
        ///	&lt;richtextbox location=&quot;12,80&quot; size=&quot;420,134&quot; name=&quot;text&quot;&gt;Введите текст&lt;/richtextbox&gt;
        ///	&lt;button location=&quot;12,220&quot; click=&quot;Click:&quot;&gt;Шифровать&lt;/button&gt;
        ///	&lt;button location=&quot;100,220&quot; click=&quot;@Click:&quot;&gt;Расшифровать&lt;/button&gt;
        ///	&lt;script&gt;
        ///Main:
        ///;
        ///Click:
        ///$var = Click(@)
        ///Compare($var,false)
        ///#text=Sapphire(#text,#key)
        ///!#text=@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LSSL {
            get {
                return ResourceManager.GetString("LSSL", resourceCulture);
            }
        }
    }
}
